# Generated by Django 5.1.4 on 2025-01-09 06:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=100)),
                ('sexe', models.IntegerField(choices=[(1, 'Homme'), (2, 'Femme')])),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(limit_choices_to={'type_utilisateur': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'detailAdmin',
            },
        ),
    ]
