# Generated by Django 5.1.4 on 2025-01-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0002_detailadmin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detailadmin',
            table='detail_admin',
        ),
    ]
