# Generated by Django 5.1.4 on 2025-01-14 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0003_alter_detailadmin_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('cin', models.CharField(max_length=50, unique=True)),
                ('sexe', models.IntegerField(choices=[(1, 'Homme'), (2, 'Femme')])),
                ('type_client', models.IntegerField(choices=[(1, 'Particulier'), (2, 'Entreprise')])),
                ('raison_social', models.CharField(max_length=100)),
                ('contact_entreprise', models.CharField(max_length=50)),
                ('date_creation_entreprise', models.DateField()),
                ('nif', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('stat', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('rcs', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('num_cnaps', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('effectif', models.IntegerField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(limit_choices_to={'type_utilisateur': 2}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'detail_client',
            },
        ),
    ]
