# Generated by Django 5.1.4 on 2025-01-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0004_detailclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailclient',
            name='adresse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detailclient',
            name='cin',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='detailclient',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detailclient',
            name='contact_entreprise',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detailclient',
            name='date_creation_entreprise',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailclient',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailclient',
            name='raison_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
