# Generated by Django 5.1.4 on 2025-01-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0005_alter_detailclient_adresse_alter_detailclient_cin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(max_length=50)),
                ('descriptions', models.TextField()),
                ('img', models.ImageField(upload_to='formations/')),
                ('disponibilite', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'db_table': 'formation',
                'ordering': ['id', 'disponibilite'],
            },
        ),
    ]
