# Generated by Django 5.1.4 on 2025-01-14 08:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0006_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='descriptions',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
