# Generated by Django 5.1.4 on 2025-01-14 10:27

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0007_alter_formation_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='modules/')),
                ('descriptions', ckeditor.fields.RichTextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree', models.DecimalField(decimal_places=2, max_digits=5)),
                ('disponibilite', models.BooleanField(default=True)),
                ('idformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='administrateur.formation')),
            ],
            options={
                'verbose_name': 'Module de formation',
                'verbose_name_plural': 'Modules de formation',
                'db_table': 'module',
                'ordering': ['id', 'idformation'],
            },
        ),
    ]
