# Generated by Django 5.1.4 on 2025-01-15 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0008_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formateur_competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idformateur', models.ForeignKey(limit_choices_to={'role_utilisateur': 3, 'type_utilisateur': 2}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idmodule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.module')),
            ],
            options={
                'db_table': 'formateur_competence',
            },
        ),
    ]
