# Generated by Django 5.1.4 on 2025-01-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0011_alter_factureinscrit_reduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturedetails',
            name='duree_seance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturedetails',
            name='nbr_seance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
