# Generated by Django 5.1.4 on 2025-01-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0013_proformanoninscrit_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformanoninscrit',
            name='facture_non_inscrit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
