# Generated by Django 5.1.4 on 2025-01-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0014_proformanoninscrit_facture_non_inscrit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factureinscrit',
            options={'ordering': ['id', 'date_creation'], 'verbose_name': 'Facture Inscrit', 'verbose_name_plural': 'Facture Inscripts'},
        ),
        migrations.AlterModelOptions(
            name='facturenoninscrit',
            options={'ordering': ['id', 'date_creation_pf'], 'verbose_name': 'Facture Non Inscrit', 'verbose_name_plural': 'Facture Non Inscripts'},
        ),
        migrations.AddField(
            model_name='factureinscrit',
            name='paiement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='facturenoninscrit',
            name='paiement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
