# Generated by Django 5.1.4 on 2025-01-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0016_alter_facturedetails_facture_non_inscrit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailadmin',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
