# Generated by Django 5.1.4 on 2025-01-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0017_detailadmin_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.IntegerField(choices=[(1, 'Transport'), (2, 'PC')])),
                ('details', models.IntegerField(blank=True, choices=[(1, 'Antananarivo-Local'), (2, 'Antananarivo-Périphérie'), (3, 'Antananarivo-Centre ville')], null=True)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'extra',
            },
        ),
    ]
