# Generated by Django 5.1.4 on 2025-02-05 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0018_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_pc',
            },
        ),
        migrations.AlterModelOptions(
            name='extra',
            options={'ordering': ['motif']},
        ),
        migrations.AlterField(
            model_name='extra',
            name='details',
            field=models.IntegerField(blank=True, choices=[(1, 'Antananarivo-Local Data Light'), (2, 'Antananarivo-Périphérie'), (3, 'Antananarivo-Centre ville'), (4, 'Région')], null=True),
        ),
        migrations.AlterField(
            model_name='extra',
            name='motif',
            field=models.IntegerField(choices=[(1, 'Transport'), (2, 'PC'), (3, 'restauration')]),
        ),
        migrations.AlterField(
            model_name='proformadetails',
            name='proforma_inscrit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='administrateur.proformainscrit'),
        ),
    ]
