# Generated by Django 5.1.5 on 2025-03-19 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0019_stockpc_alter_extra_options_alter_extra_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturedetails',
            name='facture_inscrit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='administrateur.factureinscrit'),
        ),
    ]
